# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='profile.proto',
  package='com.connectroutes.profile',
  syntax='proto3',
  serialized_options=b'Z\005proto',
  serialized_pb=b'\n\rprofile.proto\x12\x19\x63om.connectroutes.profile\"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"d\n\x16UploadDocumentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x39\n\x04\x63ode\x18\x02 \x01(\x0e\x32+.com.connectroutes.profile.UploadStatusCode\"V\n\x14UpdateProfileRequest\x12\x11\n\tfull_name\x18\x01 \x01(\t\x12\x15\n\remail_address\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\"(\n\x15UpdateProfileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t*b\n\x0c\x44ocumentType\x12\x13\n\x0fprofile_picture\x10\x00\x12\x12\n\x0e\x64river_license\x10\x01\x12\x14\n\x10vehicle_document\x10\x02\x12\x13\n\x0froad_worthiness\x10\x03*&\n\x10UploadStatusCode\x12\n\n\x06\x46\x61iled\x10\x00\x12\x06\n\x02Ok\x10\x01\x32\xf1\x01\n\x0eProfileService\x12i\n\x0eUploadDocument\x12 .com.connectroutes.profile.Chunk\x1a\x31.com.connectroutes.profile.UploadDocumentResponse\"\x00(\x01\x12t\n\rUpdateProfile\x12/.com.connectroutes.profile.UpdateProfileRequest\x1a\x30.com.connectroutes.profile.UpdateProfileResponse\"\x00\x42\x07Z\x05protob\x06proto3'
)

_DOCUMENTTYPE = _descriptor.EnumDescriptor(
  name='DocumentType',
  full_name='com.connectroutes.profile.DocumentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='profile_picture', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='driver_license', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='vehicle_document', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='road_worthiness', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=302,
  serialized_end=400,
)
_sym_db.RegisterEnumDescriptor(_DOCUMENTTYPE)

DocumentType = enum_type_wrapper.EnumTypeWrapper(_DOCUMENTTYPE)
_UPLOADSTATUSCODE = _descriptor.EnumDescriptor(
  name='UploadStatusCode',
  full_name='com.connectroutes.profile.UploadStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Failed', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ok', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=402,
  serialized_end=440,
)
_sym_db.RegisterEnumDescriptor(_UPLOADSTATUSCODE)

UploadStatusCode = enum_type_wrapper.EnumTypeWrapper(_UPLOADSTATUSCODE)
profile_picture = 0
driver_license = 1
vehicle_document = 2
road_worthiness = 3
Failed = 0
Ok = 1



_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='com.connectroutes.profile.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='com.connectroutes.profile.Chunk.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=68,
)


_UPLOADDOCUMENTRESPONSE = _descriptor.Descriptor(
  name='UploadDocumentResponse',
  full_name='com.connectroutes.profile.UploadDocumentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.connectroutes.profile.UploadDocumentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='com.connectroutes.profile.UploadDocumentResponse.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=170,
)


_UPDATEPROFILEREQUEST = _descriptor.Descriptor(
  name='UpdateProfileRequest',
  full_name='com.connectroutes.profile.UpdateProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_name', full_name='com.connectroutes.profile.UpdateProfileRequest.full_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email_address', full_name='com.connectroutes.profile.UpdateProfileRequest.email_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='com.connectroutes.profile.UpdateProfileRequest.phone_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=258,
)


_UPDATEPROFILERESPONSE = _descriptor.Descriptor(
  name='UpdateProfileResponse',
  full_name='com.connectroutes.profile.UpdateProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.connectroutes.profile.UpdateProfileResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=300,
)

_UPLOADDOCUMENTRESPONSE.fields_by_name['code'].enum_type = _UPLOADSTATUSCODE
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['UploadDocumentResponse'] = _UPLOADDOCUMENTRESPONSE
DESCRIPTOR.message_types_by_name['UpdateProfileRequest'] = _UPDATEPROFILEREQUEST
DESCRIPTOR.message_types_by_name['UpdateProfileResponse'] = _UPDATEPROFILERESPONSE
DESCRIPTOR.enum_types_by_name['DocumentType'] = _DOCUMENTTYPE
DESCRIPTOR.enum_types_by_name['UploadStatusCode'] = _UPLOADSTATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:com.connectroutes.profile.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

UploadDocumentResponse = _reflection.GeneratedProtocolMessageType('UploadDocumentResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADDOCUMENTRESPONSE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:com.connectroutes.profile.UploadDocumentResponse)
  })
_sym_db.RegisterMessage(UploadDocumentResponse)

UpdateProfileRequest = _reflection.GeneratedProtocolMessageType('UpdateProfileRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPROFILEREQUEST,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:com.connectroutes.profile.UpdateProfileRequest)
  })
_sym_db.RegisterMessage(UpdateProfileRequest)

UpdateProfileResponse = _reflection.GeneratedProtocolMessageType('UpdateProfileResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPROFILERESPONSE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:com.connectroutes.profile.UpdateProfileResponse)
  })
_sym_db.RegisterMessage(UpdateProfileResponse)


DESCRIPTOR._options = None

_PROFILESERVICE = _descriptor.ServiceDescriptor(
  name='ProfileService',
  full_name='com.connectroutes.profile.ProfileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=443,
  serialized_end=684,
  methods=[
  _descriptor.MethodDescriptor(
    name='UploadDocument',
    full_name='com.connectroutes.profile.ProfileService.UploadDocument',
    index=0,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_UPLOADDOCUMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateProfile',
    full_name='com.connectroutes.profile.ProfileService.UpdateProfile',
    index=1,
    containing_service=None,
    input_type=_UPDATEPROFILEREQUEST,
    output_type=_UPDATEPROFILERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROFILESERVICE)

DESCRIPTOR.services_by_name['ProfileService'] = _PROFILESERVICE

# @@protoc_insertion_point(module_scope)
